/*
 * Matrimonial API - OpenAPI 3.0
 *
 * Design and definition of Matrimonial APIs created for practice and teaching
 *
 * OpenAPI spec version: 1.0.11
 * Contact: floatingrays@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace MatrimonialApi.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Favourite : IEquatable<Favourite>
    { 
        /// <summary>
        /// Gets or Sets PersonId
        /// </summary>

        [DataMember(Name="personId")]
        public int? PersonId { get; set; }

        /// <summary>
        /// Gets or Sets Matchid
        /// </summary>

        [DataMember(Name="matchid")]
        public int? Matchid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Favourite {\n");
            sb.Append("  PersonId: ").Append(PersonId).Append("\n");
            sb.Append("  Matchid: ").Append(Matchid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Favourite)obj);
        }

        /// <summary>
        /// Returns true if Favourite instances are equal
        /// </summary>
        /// <param name="other">Instance of Favourite to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Favourite other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PersonId == other.PersonId ||
                    PersonId != null &&
                    PersonId.Equals(other.PersonId)
                ) && 
                (
                    Matchid == other.Matchid ||
                    Matchid != null &&
                    Matchid.Equals(other.Matchid)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (PersonId != null)
                    hashCode = hashCode * 59 + PersonId.GetHashCode();
                    if (Matchid != null)
                    hashCode = hashCode * 59 + Matchid.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Favourite left, Favourite right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Favourite left, Favourite right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
