/*
 * Matrimonial API - OpenAPI 3.0
 *
 * Design and definition of Matrimonial APIs created for practice and teaching
 *
 * OpenAPI spec version: 1.0.11
 * Contact: floatingrays@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using MatrimonialApi.Attributes;
using MatrimonialApi.Security;
using Microsoft.AspNetCore.Authorization;
using MatrimonialApi.Models;
using MatrimonialApi.Interface;
using System.Threading.Tasks;

namespace MatrimonialApi.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class AdminApiController : ControllerBase
    {
        private readonly IAdminService _adminService;

        /// <summary>
        /// Initializes a new instance of the <see cref="AdminApiController"/> class.
        /// </summary>
        /// <param name="adminService">The admin service.</param>
        public AdminApiController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        /// <summary>
        /// Add a Admin User
        /// </summary>
        /// <remarks> Add a Admin User</remarks>
        /// <param name="body"> Add a Admin User</param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid input</response>
        /// <response code="422">Validation exception</response>
        /// <response code="500">An error occured while processing the request.</response>
        /// <response code="0">Default error</response>
        [HttpPost]
        [Route("/api/admin")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("AddAdmin")]
        [SwaggerResponse(statusCode: 200, type: typeof(UserDTO), description: "Successful operation")]
        public virtual async Task<IActionResult> AddAdmin([FromBody] UserDTO body)
        {
            try
            {
                //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
                // return StatusCode(200, default(CreateAdmin));

                //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
                // return StatusCode(400);

                //TODO: Uncomment the next line to return response 422 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
                // return StatusCode(422);

                //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
                // return StatusCode(500);

                //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
                // return StatusCode(0);
                var result = await _adminService.AddAdminAsync(body);
                return Ok(result);
            }
            catch (Exception ex)
            {

                throw ex;
            }
           
        }

        /// <summary>
        /// Get Admin Users
        /// </summary>
        /// <remarks> Get Admin Users</remarks>
        /// <param name="xRequestAuth"></param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid input</response>
        /// <response code="422">Validation exception</response>
        /// <response code="500">An error occured while processing the request.</response>
        /// <response code="0">Default error</response>
        [HttpGet]
        [Route("/api/admin")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("AdminGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<AdminDTO>), description: "Successful operation")]
        public virtual async Task<IActionResult> AdminGet([FromHeader] string xRequestAuth)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<CreateAdmin>));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 422 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(422);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);
            var admins = await _adminService.GetAllAdminsAsync();
            return Ok(admins);
        }

        /// <summary>
        /// Delete a admin user
        /// </summary>
        /// <remarks>Delete a admin user</remarks>
        /// <param name="xRequestAuth"></param>
        /// <param name="adminId"></param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid input</response>
        /// <response code="422">Validation exception</response>
        /// <response code="500">An error occured while processing the request.</response>
        /// <response code="0">Default error</response>
        [HttpDelete]
        [Route("/api/admin/{adminId}")]
        [ValidateModelState]
        [SwaggerOperation("DeleteAdmin")]
        public virtual async Task<IActionResult> DeleteAdmin([FromRoute][Required] string adminId, [FromHeader][Required()] string xRequestAuth)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 422 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(422);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);

            await _adminService.DeleteAdminAsync(adminId);
            return NoContent(); // Assuming deletion does not return a resource

        }

        /// <summary>
        /// Get a admin user
        /// </summary>
        /// <remarks>get a admin user</remarks>
        /// <param name="xRequestAuth"></param>
        /// <param name="adminId"></param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid input</response>
        /// <response code="422">Validation exception</response>
        /// <response code="500">An error occured while processing the request.</response>
        /// <response code="0">Default error</response>
        [HttpGet]
        [Route("/api/admin/{adminId}")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("GetAdmin")]
        [SwaggerResponse(statusCode: 200, type: typeof(AdminDTO), description: "Successful operation")]
        public virtual async Task<IActionResult> GetAdmin([FromRoute][Required] string adminId, [FromHeader][Required()] string xRequestAuth)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(CreateAdmin));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 422 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(422);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);
            var admin = await _adminService.GetAdminByIdAsync(adminId);
            return Ok(admin);
        }

        /// <summary>
        /// Update a admin user
        /// </summary>
        /// <remarks>Update a admin user</remarks>
        /// <param name="xRequestAuth"></param>
        /// <param name="body">Update a admin</param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid input</response>
        /// <response code="422">Validation exception</response>
        /// <response code="500">An error occured while processing the request.</response>
        /// <response code="0">Default error</response>
        [HttpPut]
        [Route("/api/admin/{adminId}")]
        [ValidateModelState]
        [SwaggerOperation("UpdateAdmin")]
        public virtual async Task<IActionResult> UpdateAdmin([FromBody] UserDTO body, [FromRoute][Required] string adminId, [FromHeader] string xRequestAuth)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 422 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(422);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);

            var result = await _adminService.AddAdminAsync(body);
            return Ok(result);
        }
    }
}
