/*
 * Matrimonial API - OpenAPI 3.0
 *
 * Design and definition of Matrimonial APIs created for practice and teaching
 *
 * OpenAPI spec version: 1.0.11
 * Contact: floatingrays@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ShortProfile : IEquatable<ShortProfile>
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>

        [DataMember(Name="id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>

        [DataMember(Name="firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>

        [DataMember(Name="lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or Sets MiddleName
        /// </summary>

        [DataMember(Name="middleName")]
        public string MiddleName { get; set; }

        /// <summary>
        /// Gets or Sets ImageURL
        /// </summary>

        [DataMember(Name="imageURL")]
        public string ImageURL { get; set; }

        /// <summary>
        /// Gets or Sets CityName
        /// </summary>

        [DataMember(Name="cityName")]
        public string CityName { get; set; }

        /// <summary>
        /// Gets or Sets StateName
        /// </summary>

        [DataMember(Name="stateName")]
        public string StateName { get; set; }

        /// <summary>
        /// Gets or Sets OccupationName
        /// </summary>

        [DataMember(Name="occupationName")]
        public string OccupationName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ShortProfile {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  MiddleName: ").Append(MiddleName).Append("\n");
            sb.Append("  ImageURL: ").Append(ImageURL).Append("\n");
            sb.Append("  CityName: ").Append(CityName).Append("\n");
            sb.Append("  StateName: ").Append(StateName).Append("\n");
            sb.Append("  OccupationName: ").Append(OccupationName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ShortProfile)obj);
        }

        /// <summary>
        /// Returns true if ShortProfile instances are equal
        /// </summary>
        /// <param name="other">Instance of ShortProfile to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ShortProfile other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    FirstName == other.FirstName ||
                    FirstName != null &&
                    FirstName.Equals(other.FirstName)
                ) && 
                (
                    LastName == other.LastName ||
                    LastName != null &&
                    LastName.Equals(other.LastName)
                ) && 
                (
                    MiddleName == other.MiddleName ||
                    MiddleName != null &&
                    MiddleName.Equals(other.MiddleName)
                ) && 
                (
                    ImageURL == other.ImageURL ||
                    ImageURL != null &&
                    ImageURL.Equals(other.ImageURL)
                ) && 
                (
                    CityName == other.CityName ||
                    CityName != null &&
                    CityName.Equals(other.CityName)
                ) && 
                (
                    StateName == other.StateName ||
                    StateName != null &&
                    StateName.Equals(other.StateName)
                ) && 
                (
                    OccupationName == other.OccupationName ||
                    OccupationName != null &&
                    OccupationName.Equals(other.OccupationName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (FirstName != null)
                    hashCode = hashCode * 59 + FirstName.GetHashCode();
                    if (LastName != null)
                    hashCode = hashCode * 59 + LastName.GetHashCode();
                    if (MiddleName != null)
                    hashCode = hashCode * 59 + MiddleName.GetHashCode();
                    if (ImageURL != null)
                    hashCode = hashCode * 59 + ImageURL.GetHashCode();
                    if (CityName != null)
                    hashCode = hashCode * 59 + CityName.GetHashCode();
                    if (StateName != null)
                    hashCode = hashCode * 59 + StateName.GetHashCode();
                    if (OccupationName != null)
                    hashCode = hashCode * 59 + OccupationName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ShortProfile left, ShortProfile right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ShortProfile left, ShortProfile right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
